version: '3.8'
services:
  armareforger:
    build: .
    image: elemonator/armareforgerserver
    platform: linux/amd64
    container_name: armareforger
    network_mode: host
    volumes:
      - armareforgerroot:/armareforger
      - steamcmd:/steamcmd
      - './configs:/armareforger/configs'
      - './missions:/armareforger/mpmissions'
      - './profile:/armareforger/profile'
    env_file: .env
    # restart: unless-stopped
volumes:
  armareforgerroot:
  steamcmd:

